{"name": "test_02_login_alter_error[data0]", "status": "passed", "attachments": [{"name": "log", "source": "501c964c-c307-4e89-8352-5d84d470855a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'Caseid': 4, 'module': '登录', 'title': '错误密码登录', 'username': '18684720553', 'password': '12', 'expect': '帐号或密码错误!'}"}], "start": 1592286165896, "stop": 1592286171913, "uuid": "2e489ed3-da16-4a19-b477-0e3d39cbe0b8", "historyId": "ea1c0f90cb3f5fd8a050970d58ee5bda", "fullName": "Cases.test_login#test_02_login_alter_error[data0]", "labels": [{"name": "tag", "value": "error"}, {"name": "parentSuite", "value": "Cases"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Danny"}, {"name": "thread", "value": "14124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Cases.test_login"}]}