{"name": "test_02_login_alter_error[data1]", "status": "passed", "attachments": [{"name": "log", "source": "d704e4de-adca-4afa-9bd0-d8d8e594ff49-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'Caseid': 5, 'module': '登录', 'title': '未注册账号登录', 'username': '13541781424', 'password': '123456', 'expect': '此账号没有经过授权，请联系管理员!'}"}], "start": 1592286171917, "stop": 1592286177895, "uuid": "0c734387-d30a-458c-9e9c-02144d3de598", "historyId": "d38653b33460b7c16a92db94b238fd2a", "fullName": "Cases.test_login#test_02_login_alter_error[data1]", "labels": [{"name": "tag", "value": "error"}, {"name": "parentSuite", "value": "Cases"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Danny"}, {"name": "thread", "value": "14124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Cases.test_login"}]}